server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:11306/textexpander?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: dev
    password: dev
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: test
logging:
  level:
    org:
      springframework.web: INFO

collablynk:
  service-id: text-expander
  client-id: text-expander
  accounts-service-base-url: "http://localhost:20000"
  client-secret: "Ww4pmUOzFZo4W6cZLRTl3pN9hCwEBKNz"
